const { listSerialPorts } = require("./ports");

function readBody(req) {
  return new Promise((resolve, reject) => {
    let raw = "";

    req.on("data", (chunk) => {
      raw += chunk;
    });

    req.on("end", () => {
      if (!raw) {
        resolve({});
        return;
      }

      try {
        resolve(JSON.parse(raw));
      } catch (error) {
        reject(new Error("Invalid JSON body"));
      }
    });

    req.on("error", reject);
  });
}

function sendJson(res, statusCode, payload) {
  res.writeHead(statusCode, { "Content-Type": "application/json; charset=utf-8" });
  res.end(JSON.stringify(payload));
}

function parseIntStrict(value) {
  const next = Number(value);
  if (!Number.isFinite(next) || !Number.isInteger(next)) {
    return null;
  }
  return next;
}

function withWorldPositions(players, world) {
  const positionMap = world.playerPositions || {};
  return players.map((player) => {
    const position = positionMap[player.nodeId] || null;
    return {
      ...player,
      position
    };
  });
}

function createApiHandler({ store, meshtasticService }) {
  return async (req, res, url) => {
    if (req.method === "DELETE" && url.pathname.startsWith("/api/players/")) {
      const nodeId = decodeURIComponent(url.pathname.slice("/api/players/".length));
      if (!nodeId) {
        sendJson(res, 400, { error: "Missing player nodeId" });
        return;
      }

      const removed = store.deletePlayer(nodeId);
      if (!removed) {
        sendJson(res, 404, { error: `Player not found: ${nodeId}` });
        return;
      }

      store.removePlayerPosition(nodeId);
      store.appendLog("admin", `Player deleted: ${nodeId}`);
      sendJson(res, 200, { ok: true });
      return;
    }

    if (req.method === "GET" && url.pathname === "/api/state") {
      const world = store.getWorld();
      const players = withWorldPositions(store.getPlayers(), world);
      sendJson(res, 200, {
        device: meshtasticService.getStatus(),
        players,
        logs: store.getLogs(),
        world
      });
      return;
    }

    if (req.method === "GET" && url.pathname === "/api/world") {
      sendJson(res, 200, { world: store.getWorld() });
      return;
    }

    if (req.method === "POST" && url.pathname === "/api/world/config") {
      const body = await readBody(req);
      const width = parseIntStrict(body.width);
      const height = parseIntStrict(body.height);
      if (width === null || height === null) {
        sendJson(res, 400, { error: "width and height must be integers" });
        return;
      }

      const world = store.resizeWorld(width, height);
      store.appendLog("admin", `World resized to ${world.map.width}x${world.map.height}`);
      sendJson(res, 200, { world });
      return;
    }

    if (req.method === "POST" && url.pathname === "/api/world/meta") {
      const body = await readBody(req);
      const world = store.getWorld();
      const name = String(body.name || "").trim().slice(0, 40) || "Untitled Map";
      const saved = store.saveWorld({
        ...world,
        name
      });
      store.appendLog("admin", `World renamed to ${saved.name}`);
      sendJson(res, 200, { world: saved });
      return;
    }

    if (req.method === "POST" && url.pathname === "/api/world/generate") {
      const body = await readBody(req);
      const width = body.width === undefined ? undefined : parseIntStrict(body.width);
      const height = body.height === undefined ? undefined : parseIntStrict(body.height);
      const seed = body.seed === undefined ? undefined : Number(body.seed);

      if ((body.width !== undefined && width === null) || (body.height !== undefined && height === null)) {
        sendJson(res, 400, { error: "width and height must be integers" });
        return;
      }

      if (body.seed !== undefined && !Number.isFinite(seed)) {
        sendJson(res, 400, { error: "seed must be numeric" });
        return;
      }

      const world = store.generateWorld({ width, height, seed });
      store.appendLog(
        "admin",
        `World autogenerated (${world.map.width}x${world.map.height}, entities=${world.entities.length})`
      );
      sendJson(res, 200, { world });
      return;
    }

    if (req.method === "POST" && url.pathname === "/api/world/import") {
      const body = await readBody(req);
      const worldInput = body && typeof body === "object" && body.world ? body.world : body;
      if (!worldInput || typeof worldInput !== "object") {
        sendJson(res, 400, { error: "world payload is required" });
        return;
      }
      const world = store.saveWorld(worldInput);
      store.appendLog("admin", `World imported (${world.map.width}x${world.map.height}, entities=${world.entities.length})`);
      sendJson(res, 200, { world });
      return;
    }

    if (req.method === "POST" && url.pathname === "/api/world/clear") {
      const world = store.getWorld();
      const nextTiles = {};
      for (let y = 0; y < world.map.height; y += 1) {
        for (let x = 0; x < world.map.width; x += 1) {
          nextTiles[`${x},${y}`] = {
            terrain: "plain",
            blocked: false,
            label: ""
          };
        }
      }

      const clearedWorld = store.saveWorld({
        ...world,
        map: {
          ...world.map,
          tiles: nextTiles
        },
        entities: [],
        landClaims: {},
        marketOffers: []
      });

      const players = store.getPlayers().map((player) => {
        const gameState = player.gameState && typeof player.gameState === "object" ? player.gameState : {};
        return {
          ...player,
          updatedAt: new Date().toISOString(),
          gameState: {
            ...gameState,
            claimedCells: [],
            buildings: {},
            cityCore: null,
            cityName: "",
            cityLevel: 1
          }
        };
      });
      store.savePlayers(players);

      store.appendLog("admin", `World cleared to plain terrain (${clearedWorld.map.width}x${clearedWorld.map.height})`);
      sendJson(res, 200, { world: clearedWorld });
      return;
    }

    if (req.method === "POST" && url.pathname === "/api/world/tile") {
      const body = await readBody(req);
      const x = parseIntStrict(body.x);
      const y = parseIntStrict(body.y);
      if (x === null || y === null) {
        sendJson(res, 400, { error: "x and y must be integers" });
        return;
      }

      const world = store.upsertWorldTile(x, y, {
        terrain: body.terrain,
        blocked: body.blocked,
        label: body.label
      });
      store.appendLog("admin", `Tile updated at ${x},${y}`);
      sendJson(res, 200, { world });
      return;
    }

    if (req.method === "POST" && url.pathname === "/api/world/entity") {
      const body = await readBody(req);
      const x = parseIntStrict(body.x);
      const y = parseIntStrict(body.y);
      if (x === null || y === null) {
        sendJson(res, 400, { error: "x and y must be integers" });
        return;
      }

      const world = store.upsertWorldEntity({
        id: body.id,
        type: body.type,
        name: body.name,
        x,
        y,
        hp: body.hp,
        meta: body.meta
      });
      store.appendLog("admin", `Entity saved at ${x},${y}: ${body.name || body.type || "entity"}`);
      sendJson(res, 200, { world });
      return;
    }

    if (req.method === "DELETE" && url.pathname.startsWith("/api/world/entity/")) {
      const entityId = decodeURIComponent(url.pathname.slice("/api/world/entity/".length));
      if (!entityId) {
        sendJson(res, 400, { error: "Missing entity id" });
        return;
      }

      const result = store.deleteWorldEntity(entityId);
      if (!result.removed) {
        sendJson(res, 404, { error: `Entity not found: ${entityId}` });
        return;
      }
      store.appendLog("admin", `Entity deleted: ${entityId}`);
      sendJson(res, 200, { world: result.world });
      return;
    }

    if (req.method === "POST" && url.pathname === "/api/world/player-position") {
      const body = await readBody(req);
      const nodeId = String(body.nodeId || "").trim();
      const x = parseIntStrict(body.x);
      const y = parseIntStrict(body.y);
      if (!nodeId || x === null || y === null) {
        sendJson(res, 400, { error: "nodeId, x, y are required" });
        return;
      }

      const existing = store.getPlayers().some((player) => player.nodeId === nodeId);
      if (!existing) {
        sendJson(res, 404, { error: `Player not found: ${nodeId}` });
        return;
      }

      const world = store.getWorld();
      const tile = world.map.tiles[`${x},${y}`] || { terrain: "plain", blocked: false };
      if (tile.blocked || tile.terrain === "water") {
        sendJson(res, 400, { error: tile.terrain === "water" ? "Players cannot be moved into water" : "Tile is blocked" });
        return;
      }

      const savedWorld = store.setPlayerPosition(nodeId, x, y);
      store.appendLog("admin", `Player ${nodeId} moved to ${x},${y}`);
      sendJson(res, 200, { world: savedWorld });
      return;
    }

    if (req.method === "GET" && url.pathname === "/api/device/ports") {
      const ports = await listSerialPorts();
      sendJson(res, 200, { ports });
      return;
    }

    if (req.method === "POST" && url.pathname === "/api/device/connect") {
      const body = await readBody(req);
      const device = meshtasticService.connect(body.transport || "simulation", {
        port: body.port || null
      });
      sendJson(res, 200, { device });
      return;
    }

    if (req.method === "POST" && url.pathname === "/api/device/disconnect") {
      const device = meshtasticService.disconnect();
      sendJson(res, 200, { device });
      return;
    }

    if (req.method === "POST" && url.pathname === "/api/logs/clear") {
      store.clearLogs();
      store.appendLog("admin", "Logs cleared");
      sendJson(res, 200, { ok: true });
      return;
    }

    if (req.method === "GET" && url.pathname === "/api/export/players") {
      res.writeHead(200, {
        "Content-Type": "application/json; charset=utf-8",
        "Content-Disposition": "attachment; filename=players.json"
      });
      res.end(JSON.stringify({ players: store.getPlayers() }, null, 2));
      return;
    }

    sendJson(res, 404, { error: `Route not found: ${req.method} ${url.pathname}` });
  };
}

module.exports = {
  createApiHandler
};
